## Login as user madrugasx
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "madrugasx",
    "password": "salada"
}

###

### Login as root user
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}

###

### User maduragasx token below
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZHJ1Z2FzeCIsImlkIjoiNjhmZWM1NjExOTUyZTdmNWM2ZTE1MGU3IiwiaWF0IjoxNzYxODYyMjM0fQ.iMCIxx-1BX-ookHJhYnIBTnW9HDRqXdBj0u7uS3TAL4

{
    "title": "Linkedin Site",
    "author": "Linkedin Corporation",
    "url": "linkedin.com",
    "likes": 0
}

###

### User root token below
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4ZmVjNTNiMTk1MmU3ZjVjNmUxNTBlNSIsImlhdCI6MTc2MTg3MzgwNH0.en4jPPoggpUER78OQwPlUH1mAgGr_1jvOC7AaCKFWLk

{
    "title": "Blog com middleware",
    "author": "Root",
    "url": "https://exemplo.com",
    "likes": 0
}

###

### Get all blogs
GET http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZHJ1Z2FzeCIsImlkIjoiNjhmZWM1NjExOTUyZTdmNWM2ZTE1MGU3IiwiaWF0IjoxNzYxODYyMjM0fQ.iMCIxx-1BX-ookHJhYnIBTnW9HDRqXdBj0u7uS3TAL4

###

### Get all users
GET http://localhost:3003/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZHJ1Z2FzeCIsImlkIjoiNjhmZWM1NjExOTUyZTdmNWM2ZTE1MGU3IiwiaWF0IjoxNzYxODYyMjM0fQ.iMCIxx-1BX-ookHJhYnIBTnW9HDRqXdBj0u7uS3TAL4

###

### Delete a blog
DELETE http://localhost:3003/api/blogs/690bf67a72ff5c1fedae8097
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4ZmVjNTNiMTk1MmU3ZjVjNmUxNTBlNSIsImlhdCI6MTc2MjM5MTgzNH0.8j9TZOUSx3ndwSKcKZow3Nup2zB6EUFGmmya_fiKrAw

###

### Error: shorter username
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "ma",
  "password": "salada"
}

###

### Error: shorter password
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "madrugasx2",
  "password": "sa"
}

###

### Error: username already taken
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "madrugasx",
  "password": "outrasenha"
}

###

### Error: invalid user data
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Teste"
}

### Criar novo blog (sem token, sem user no body)
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Novo Blog Automático",
  "author": "Autor X",
  "url": "https://exemplo.com",
  "likes": 0
}

###

### Listar todos os blogs com usuário
GET http://localhost:3003/api/blogs